## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('sdattackdsr', ['core', 'network', 'internet', 'applications', 'mobility', 'config-store', 'wifi', 'sdattackdsr'])
    obj.source = 'sdattackdsr.cc'

