## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('rushattackdsr', ['core', 'network', 'internet', 'applications', 'mobility', 'config-store', 'wifi', 'rushattackdsr'])
    obj.source = 'rushattackdsr.cc'

